FROM debian:trixie-slim

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY build/native/nativeCompile/server /home/container/server
COPY run/ /home/container/

CMD ["/bin/bash", "-c", "\
MODIFIED_STARTUP=$(echo \"$STARTUP\" | sed -e 's/{{/${/g' -e 's/}}/}/g'); \
eval \"$MODIFIED_STARTUP\" \
"]
