FROM debian:trixie-slim

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY build/native/nativeCompile/server /server
COPY run/ /

COPY ./entrypoint.sh /entrypoint.sh
CMD [ "/bin/bash", "/entrypoint.sh" ]
